# Auto-generated by seed data spreadsheet.
electric_zoo = Festival.where(name: 'Electric Zoo', location: 'New York, NY', description: "Made Event presents Electric Zoo, New York's Electronic ...", start_date:  Date.new(2014, 8, 29), end_date: Date.new(2014, 8, 31)).first_or_create
tomorrowworld = Festival.where(name: 'TomorrowWorld', location: 'Atlanta, GA', description: 'Vestibulum id ligula porta felis euismod semper. Maecenas faucibus mollis interdum.', start_date:  Date.new(2014, 9, 26), end_date: Date.new(2014, 9, 28)).first_or_create
decibel = Festival.where(name: 'Decibel', location: 'Seattle, WA', description: 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.', start_date:  Date.new(2014, 9, 24), end_date: Date.new(2014, 9, 28)).first_or_create
bpm = Festival.where(name: 'BPM', location: 'Playa del Carmen, Mexico', description: 'Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.', start_date:  Date.new(2015, 1, 9), end_date: Date.new(2015, 1, 18)).first_or_create
boston_calling = Festival.where(name: 'Boston Calling', location: 'Boston, MA', description: 'Donec ullamcorper nulla non metus auctor fringilla. Nullam quis risus eget urna mollis ornare vel eu leo.', start_date:  Date.new(2014, 9, 5), end_date: Date.new(2014, 9, 7)).first_or_create
lollapalooza = Festival.where(name: 'Lollapalooza', location: 'Chicago, IL', description: 'Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Cras mattis consectetur purus sit amet fermentum. Donec id elit non mi porta gravida at eget metus.', start_date:  Date.new(2014, 8, 1), end_date: Date.new(2014, 8, 3)).first_or_create

stage_1 = Venue.where(name: 'Stage 1', festival: decibel).first_or_create
stage_2 = Venue.where(name: 'Stage 2', festival: decibel).first_or_create
stage_3 = Venue.where(name: 'Stage 3', festival: decibel).first_or_create

alan_fitzpatrick = Artist.where(name: 'Alan Fitzpatrick', soundcloud_url: 'https://soundcloud.com/alanfitzpatrick', soundcloud_track_url: 'https://soundcloud.com/mvsic-io/sets/alan-fitzpatrick').first_or_create
alesso = Artist.where(name: 'Alesso', soundcloud_url: 'https://soundcloud.com/alesso', soundcloud_track_url: 'https://soundcloud.com/alesso/alesso-bbc-radio1-new-years').first_or_create
alvin_risk = Artist.where(name: 'Alvin Risk', soundcloud_url: 'https://soundcloud.com/alvinrisk', soundcloud_track_url: 'https://soundcloud.com/alvinrisk/weareyoung').first_or_create
ame = Artist.where(name: 'Âme', soundcloud_url: 'https://soundcloud.com/ame', soundcloud_track_url: 'https://soundcloud.com/carharttwip/carhartt-wip-radio-june-2014').first_or_create
andrea_oliva = Artist.where(name: 'Andrea Oliva', soundcloud_url: 'https://soundcloud.com/andreaoliva', soundcloud_track_url: 'https://soundcloud.com/andreaoliva/andrea-oliva-defected-in-the').first_or_create
apollonia = Artist.where(name: 'Apollonia', soundcloud_url: 'https://soundcloud.com/apolloniamusic', soundcloud_track_url: 'https://soundcloud.com/mixmag-1/apollonia-live-from-the-mixmag').first_or_create
armin_van_buuren = Artist.where(name: 'Armin van Buuren', soundcloud_url: 'https://soundcloud.com/arminvanbuuren', soundcloud_track_url: 'https://soundcloud.com/arminvanbuuren/idina-menzel-let-it-go-armin').first_or_create
arty = Artist.where(name: 'Arty', soundcloud_url: 'https://soundcloud.com/artyofficial', soundcloud_track_url: 'https://soundcloud.com/londongrammar/hey-now-arty-remix').first_or_create
atb = Artist.where(name: 'ATB', soundcloud_url: '', soundcloud_track_url: 'https://soundcloud.com/ultramiamitrance2013/atb-ultra-music-festival-miami-2013').first_or_create
a_trak = Artist.where(name: 'A-Trak', soundcloud_url: 'https://soundcloud.com/a-trak', soundcloud_track_url: 'https://soundcloud.com/ducksaucenyc/duck-sauce-presents-duck-tape').first_or_create
audien = Artist.where(name: 'Audien', soundcloud_url: 'https://soundcloud.com/audien', soundcloud_track_url: 'https://soundcloud.com/audien/audien-ultra-miami-2014').first_or_create
been_trill = Artist.where(name: 'Been Trill', soundcloud_url: 'https://soundcloud.com/been_trill', soundcloud_track_url: 'https://soundcloud.com/been_trill/01-bbc-1-radio-1-mix-5-30-12').first_or_create
benny_benassi = Artist.where(name: 'Benny Benassi', soundcloud_url: 'https://soundcloud.com/benny-benassi', soundcloud_track_url: 'https://soundcloud.com/mixes/benny-benassi-john-dahlback-edmcom-exclusive-mix').first_or_create
bingo_players = Artist.where(name: 'Bingo Players', soundcloud_url: 'https://soundcloud.com/bingoplayers', soundcloud_track_url: 'https://soundcloud.com/bingoplayers/live-at-edc-las-vegas-2014').first_or_create
bonobo = Artist.where(name: 'Bonobo', soundcloud_url: 'https://soundcloud.com/bonobo', soundcloud_track_url: 'https://soundcloud.com/bonobo/essential-mix').first_or_create
borgeous = Artist.where(name: 'Borgeous', soundcloud_url: 'https://soundcloud.com/borgeousmusic', soundcloud_track_url: 'https://soundcloud.com/borgeousmusic/dvbbs-borgeous-tsunami').first_or_create
brillz = Artist.where(name: 'Brillz', soundcloud_url: 'https://soundcloud.com/itsbrillz', soundcloud_track_url: 'https://soundcloud.com/itsbrillz/diplo-friends-twonk-takeover').first_or_create
bt = Artist.where(name: 'BT', soundcloud_url: 'https://soundcloud.com/bt', soundcloud_track_url: 'https://soundcloud.com/bt/bt-guest-mix-for-group-therapy').first_or_create
caked_up = Artist.where(name: 'Caked Up', soundcloud_url: 'https://soundcloud.com/eatdatcake', soundcloud_track_url: 'https://soundcloud.com/eatdatcake/wrecking-ball-caked-up-remix').first_or_create
candyland = Artist.where(name: 'Candyland', soundcloud_url: 'https://soundcloud.com/candylanddjs', soundcloud_track_url: 'https://soundcloud.com/clockwork/clockwork-live-mad-decent').first_or_create
carlo_lio = Artist.where(name: 'Carlo Lio', soundcloud_url: 'https://soundcloud.com/carlolio', soundcloud_track_url: 'https://soundcloud.com/carlolio/music-on-mix-2013').first_or_create
carnage = Artist.where(name: 'Carnage', soundcloud_url: 'https://soundcloud.com/djcarnageofficial', soundcloud_track_url: 'https://soundcloud.com/djcarnageofficial/carnage-live-electric-daisy').first_or_create
cazzette = Artist.where(name: 'Cazzette', soundcloud_url: 'https://soundcloud.com/cazzette', soundcloud_track_url: 'https://soundcloud.com/djcarnageofficial/carnage-live-electric-daisy').first_or_create
chase_and_status = Artist.where(name: 'Chase & Status', soundcloud_url: 'https://soundcloud.com/chaseandstatus', soundcloud_track_url: 'https://soundcloud.com/chaseandstatus/blk-blu-feat-ed-thomas').first_or_create
chris_liebing = Artist.where(name: 'Chris Liebing', soundcloud_url: 'https://soundcloud.com/chris-liebing', soundcloud_track_url: 'https://soundcloud.com/chris-liebing/moby-lie-down-in-darkness-2').first_or_create
clockwork = Artist.where(name: 'Clockwork', soundcloud_url: 'https://soundcloud.com/clockwork', soundcloud_track_url: 'https://soundcloud.com/clockwork/clockwork-live-mad-decent').first_or_create
cosmic_gate = Artist.where(name: 'Cosmic Gate', soundcloud_url: 'https://soundcloud.com/cosmicgateofficial', soundcloud_track_url: 'https://soundcloud.com/cosmicgateofficial/cosmic-gate-ultra-music').first_or_create
dada_life = Artist.where(name: 'Dada Life', soundcloud_url: 'https://soundcloud.com/dada-life', soundcloud_track_url: 'https://soundcloud.com/dada-life/live-at-electric-zoo-2013').first_or_create
danny_avila = Artist.where(name: 'Danny Avila', soundcloud_url: 'https://soundcloud.com/dannyavila', soundcloud_track_url: 'https://soundcloud.com/dannyavila/danny-avila-bbc-radio-1s-residency-guest-mix').first_or_create
danny_tenaglia = Artist.where(name: 'Danny Tenaglia', soundcloud_url: 'https://soundcloud.com/danny-tenaglia-official', soundcloud_track_url: 'https://soundcloud.com/danny-tenaglia-official/danny-tenaglia-dj-mix-for').first_or_create
dash_berlin = Artist.where(name: 'Dash Berlin', soundcloud_url: 'https://soundcloud.com/dashberlin', soundcloud_track_url: 'https://soundcloud.com/dashberlin/dash-berlin-edc-2014-live-set-weare').first_or_create
datsik = Artist.where(name: 'Datsik', soundcloud_url: 'https://soundcloud.com/datsik', soundcloud_track_url: 'https://soundcloud.com/datsik/datsik-umf-firepower-showcase').first_or_create
david_guetta = Artist.where(name: 'David Guetta', soundcloud_url: 'https://soundcloud.com/davidguetta', soundcloud_track_url: 'https://soundcloud.com/edmnations-com/david-guetta-live-ultra-music').first_or_create
david_solano = Artist.where(name: 'David Solano', soundcloud_url: 'https://soundcloud.com/david-solano', soundcloud_track_url: 'https://soundcloud.com/david-solano/adventure-club-david-solano-ft').first_or_create
deniz_koyu = Artist.where(name: 'Deniz Koyu', soundcloud_url: 'https://soundcloud.com/denizkoyu', soundcloud_track_url: 'https://soundcloud.com/denizkoyu/deniz-koyu-bongbastic-045').first_or_create
deorro = Artist.where(name: 'Deorro', soundcloud_url: 'https://soundcloud.com/deorro', soundcloud_track_url: 'https://soundcloud.com/edmchicagorecords/deorro-live-edc-las-vegas-2014').first_or_create
destroid = Artist.where(name: 'Destroid', soundcloud_url: 'https://soundcloud.com/destroid', soundcloud_track_url: 'https://soundcloud.com/dubstep/destroid-annihilate-datsik-remix-edmcom-premiere').first_or_create
dimitri_vegas_and_like_mike = Artist.where(name: 'Dimitri Vegas & Like Mike', soundcloud_url: 'https://soundcloud.com/dimitrivegasandlikemike', soundcloud_track_url: 'https://soundcloud.com/dimitrivegasandlikemike/dimitri-vegas-like-mike-bbc').first_or_create
dirty_south = Artist.where(name: 'Dirty South', soundcloud_url: 'https://soundcloud.com/dirtysouth', soundcloud_track_url: 'https://soundcloud.com/dirtysouth/edc-ny-2013-dirty-south').first_or_create
dirtyphonics = Artist.where(name: 'Dirtyphonics', soundcloud_url: 'https://soundcloud.com/dirtyphonics', soundcloud_track_url: 'https://soundcloud.com/dirtyphonics/shambhala-mix-2013').first_or_create
dubfire = Artist.where(name: 'Dubfire', soundcloud_url: 'https://soundcloud.com/dubfire-music', soundcloud_track_url: 'https://soundcloud.com/dubfire-music/part-1-show-1').first_or_create
dvbbs = Artist.where(name: 'DVBBS', soundcloud_url: 'https://soundcloud.com/dvbbs', soundcloud_track_url: 'https://soundcloud.com/spinninsessions/spinnin-sessions-035-guest-1').first_or_create
dyro = Artist.where(name: 'Dyro', soundcloud_url: 'https://soundcloud.com/dyromusic', soundcloud_track_url: 'https://soundcloud.com/dyromusic/dyro-presents-daftastic-radio-special-live-edc-las-vegas-2014-download').first_or_create
fedde_le_grand = Artist.where(name: 'Fedde Le Grand', soundcloud_url: 'https://soundcloud.com/feddelegrand', soundcloud_track_url: 'https://soundcloud.com/feddelegrand/fedde-le-grand-live-at-ultra-2014').first_or_create
feenixpawl = Artist.where(name: 'Feenixpawl', soundcloud_url: 'https://soundcloud.com/feenixpawl', soundcloud_track_url: 'https://soundcloud.com/earmilk/feenixpawl-afterhours-mix-earmilk-exclusive').first_or_create
fehrplay = Artist.where(name: 'Fehrplay', soundcloud_url: 'https://soundcloud.com/fehrplay', soundcloud_track_url: 'https://soundcloud.com/dancingastronaut/axis-078').first_or_create
felix_cartal = Artist.where(name: 'Felix Cartal', soundcloud_url: 'https://soundcloud.com/felixcartal', soundcloud_track_url: 'https://soundcloud.com/felixcartal/felix-cartal-after-dark-live').first_or_create
figure = Artist.where(name: 'Figure', soundcloud_url: 'https://soundcloud.com/figure', soundcloud_track_url: 'https://soundcloud.com/figure/figure-monster-mania-original').first_or_create
firebeatz = Artist.where(name: 'Firebeatz', soundcloud_url: 'https://soundcloud.com/firebeatz', soundcloud_track_url: 'https://soundcloud.com/firebeatz/firebeatz-live-edc-las-vegas-2014').first_or_create
gesaffelstein = Artist.where(name: 'Gesaffelstein', soundcloud_url: 'https://soundcloud.com/gesaffelstein', soundcloud_track_url: 'https://soundcloud.com/gesaffelstein/pursuit').first_or_create
gladiator = Artist.where(name: 'Gladiator', soundcloud_url: 'https://soundcloud.com/gladiatormusic', soundcloud_track_url: 'https://soundcloud.com/borgore/the-borgore-show-on-siriusxm-13').first_or_create
gorgon_city = Artist.where(name: 'Gorgon City', soundcloud_url: 'https://soundcloud.com/gorgon-city', soundcloud_track_url: 'https://soundcloud.com/mixmag-1/in-session-gorgon-city').first_or_create
griz = Artist.where(name: 'GRiZ', soundcloud_url: 'https://soundcloud.com/griz', soundcloud_track_url: 'https://soundcloud.com/griz/smash-the-funk-forthcoming').first_or_create
henry_fong = Artist.where(name: 'Henry Fong', soundcloud_url: 'https://soundcloud.com/henryfong', soundcloud_track_url: 'https://soundcloud.com/henryfong/edc-vegas-2014').first_or_create
heroes_x_villains = Artist.where(name: 'Heroes x Villains', soundcloud_url: 'https://soundcloud.com/heroesxvillains', soundcloud_track_url: 'https://soundcloud.com/heroesxvillains/daniel-disaster-of-heroes-x').first_or_create
hook_n_sling = Artist.where(name: 'Hook N Sling', soundcloud_url: 'https://soundcloud.com/hooknsling', soundcloud_track_url: 'https://soundcloud.com/hooknsling/magnet-mixtape').first_or_create
hot_since_82 = Artist.where(name: 'Hot Since 82', soundcloud_url: 'https://soundcloud.com/hotsince-82', soundcloud_track_url: 'https://soundcloud.com/hotsince-82/hot-since-82-knee-deep-in-2013').first_or_create
jack_u = Artist.where(name: 'Jack U', soundcloud_url: 'https://soundcloud.com/jack-u', soundcloud_track_url: 'https://soundcloud.com/nickraymondg/jack-u-diplo-and-skrillex').first_or_create
jamie_xx = Artist.where(name: 'Jamie XX', soundcloud_url: '', soundcloud_track_url: 'https://soundcloud.com/youngturks/jamie-xx-essential-mix').first_or_create
jeremy_olander = Artist.where(name: 'Jeremy Olander', soundcloud_url: 'https://soundcloud.com/jeremyolander', soundcloud_track_url: 'https://soundcloud.com/change-underground/change-underground-presents-jeremy-olander').first_or_create
joel_mull = Artist.where(name: 'Joel Mull', soundcloud_url: 'https://soundcloud.com/joelmull', soundcloud_track_url: 'https://soundcloud.com/invite-1/invites-choice-podcast-132').first_or_create
joseph_capriati = Artist.where(name: 'Joseph Capriati', soundcloud_url: 'https://soundcloud.com/joseph-capriati', soundcloud_track_url: 'https://soundcloud.com/joseph-capriati/joseph-capriati-at-circoloco').first_or_create
josh_wink = Artist.where(name: 'Josh Wink', soundcloud_url: 'https://soundcloud.com/phillywink', soundcloud_track_url: 'https://soundcloud.com/fabric/josh-wink-fabric-promo-mix').first_or_create
kaskade = Artist.where(name: 'Kaskade', soundcloud_url: 'https://soundcloud.com/kaskade', soundcloud_track_url: 'https://soundcloud.com/kaskade/kaskade-live-at-ultra-music-1').first_or_create
keys_n_krates = Artist.where(name: 'Keys N Krates', soundcloud_url: 'https://soundcloud.com/keysnkrates', soundcloud_track_url: 'https://soundcloud.com/keysnkrates/keys-n-krates-diplo-friends-mix-41214-bbc-radio1').first_or_create
kidnap_kid = Artist.where(name: 'Kidnap Kid', soundcloud_url: 'https://soundcloud.com/kidnap_kid', soundcloud_track_url: 'https://soundcloud.com/thump/mixed-by-kidnap-kid').first_or_create
kill_paris = Artist.where(name: 'Kill Paris', soundcloud_url: 'https://soundcloud.com/killparis', soundcloud_track_url: 'https://soundcloud.com/killparis/kill-paris-now-thats-what-i').first_or_create
kill_the_noise = Artist.where(name: 'Kill the Noise', soundcloud_url: 'https://soundcloud.com/killthenoise', soundcloud_track_url: 'https://soundcloud.com/killthenoise/bbc-1xtra-kill-the-noise-owsla').first_or_create
knife_party = Artist.where(name: 'Knife Party', soundcloud_url: 'https://soundcloud.com/knifepartyinc', soundcloud_track_url: 'https://soundcloud.com/knifepartyinc/knife-party-live-at-ultra').first_or_create
kove = Artist.where(name: 'Kove', soundcloud_url: 'https://soundcloud.com/kove', soundcloud_track_url: 'https://soundcloud.com/kove/guestmix-for-mistajam').first_or_create
laidback_luke = Artist.where(name: 'Laidback Luke', soundcloud_url: 'https://soundcloud.com/laidbackluke', soundcloud_track_url: 'https://soundcloud.com/laidbackluke/laidback-luke-yearmix-2013').first_or_create
late_night_alumni = Artist.where(name: 'Late Night Alumni', soundcloud_url: 'https://soundcloud.com/latenightalumni', soundcloud_track_url: 'https://soundcloud.com/latenightalumni/becky-jean-williams-tribute-1').first_or_create
le_castle_vania = Artist.where(name: 'Le Castle Vania', soundcloud_url: 'https://soundcloud.com/lecastlevania', soundcloud_track_url: 'https://soundcloud.com/lecastlevania/30min-mau5trap-mix').first_or_create
loudpvck = Artist.where(name: 'LOUDPVCK', soundcloud_url: 'https://soundcloud.com/loudpvck', soundcloud_track_url: 'https://soundcloud.com/nickraymondg/loudpvck-full-melt-mix').first_or_create
madeon = Artist.where(name: 'Madeon', soundcloud_url: 'https://soundcloud.com/madeon', soundcloud_track_url: 'https://soundcloud.com/madeon/madeon-live-triple-j-mix').first_or_create
makj = Artist.where(name: 'MAKJ', soundcloud_url: 'https://soundcloud.com/makj', soundcloud_track_url: 'https://soundcloud.com/makj/gdd-makj-mix').first_or_create
mat_zo = Artist.where(name: 'Mat Zo', soundcloud_url: 'https://soundcloud.com/mat_zo', soundcloud_track_url: 'https://soundcloud.com/mat_zo/the-mat-zo-mix-020-28-06-14-edc-2014').first_or_create
milo_and_otis = Artist.where(name: 'Milo & Otis', soundcloud_url: 'https://soundcloud.com/miloandotis', soundcloud_track_url: 'https://soundcloud.com/djcarnageofficial/episode-013').first_or_create
morgan_page = Artist.where(name: 'Morgan Page', soundcloud_url: 'https://soundcloud.com/morganpage', soundcloud_track_url: 'https://soundcloud.com/morganpage/morgan-page-live-at-edc-las-1').first_or_create
moti = Artist.where(name: 'MOTi', soundcloud_url: 'https://soundcloud.com/motiofficial', soundcloud_track_url: 'https://soundcloud.com/motiofficial/moti-circuitgrounds-edc-las-vegas-2014').first_or_create
myon_and_shane_54 = Artist.where(name: 'Myon & Shane 54', soundcloud_url: 'https://soundcloud.com/myonandshane54', soundcloud_track_url: 'https://soundcloud.com/ultra2014-livesets/myon-shane-54-live-at-asot-650-ultra-music-festival-miami-2014-30-03-2014').first_or_create
nervo = Artist.where(name: 'Nervo', soundcloud_url: 'https://soundcloud.com/nervomusic', soundcloud_track_url: 'https://soundcloud.com/nervomusic/nervo-bbc-radio-1-essential-mix').first_or_create
netsky = Artist.where(name: 'Netsky', soundcloud_url: 'https://soundcloud.com/netsky', soundcloud_track_url: 'https://soundcloud.com/acunixx-1/netsky-essential-mix-09-10-2010').first_or_create
new_world_sound = Artist.where(name: 'New World Sound', soundcloud_url: 'https://soundcloud.com/newworldsound', soundcloud_track_url: 'https://soundcloud.com/le7els-records/new-world-sound-le7els-mixtape').first_or_create
nicky_romero = Artist.where(name: 'Nicky Romero', soundcloud_url: 'https://soundcloud.com/nickyromero', soundcloud_track_url: 'https://soundcloud.com/nickyromero/nicky-romero-ultra-music-1').first_or_create
nicole_moudaber = Artist.where(name: 'Nicole Moudaber', soundcloud_url: 'https://soundcloud.com/nicolemoudaber', soundcloud_track_url: 'https://soundcloud.com/nicolemoudaber/nicole-moudaber-live-cacao').first_or_create
oliver_heldens = Artist.where(name: 'Oliver Heldens', soundcloud_url: 'https://soundcloud.com/oliverheldens', soundcloud_track_url: 'https://soundcloud.com/spinninsessions/spinnin-sessions-048-guest').first_or_create
ookay_b2b_kennedy_jones = Artist.where(name: 'Ookay B2B Kennedy Jones', soundcloud_url: 'https://soundcloud.com/ookaymusic', soundcloud_track_url: 'https://soundcloud.com/marqueenightclub/kennedy-jones-marquee-mix').first_or_create
otto_knows = Artist.where(name: 'Otto Knows', soundcloud_url: 'https://soundcloud.com/otto-knows', soundcloud_track_url: 'https://soundcloud.com/otto-knows/pete-tongs-young-stars-on-bbc').first_or_create
paris_blohm = Artist.where(name: 'Paris Blohm', soundcloud_url: 'https://soundcloud.com/parisblohm', soundcloud_track_url: 'https://soundcloud.com/parisblohm/paris-blohm-tss-mixify-set-v2').first_or_create
paul_van_dyk = Artist.where(name: 'Paul van Dyk', soundcloud_url: 'https://soundcloud.com/paulvandykofficial', soundcloud_track_url: 'https://soundcloud.com/paulvandykofficial/paul-van-dyks-end-of-summer-essential-mix').first_or_create
pegboard_nerds = Artist.where(name: 'Pegboard Nerds', soundcloud_url: 'https://soundcloud.com/pegboardnerds', soundcloud_track_url: 'https://soundcloud.com/pegboardnerds/pegboard-nerds-hero-ft-elizaveta').first_or_create
pete_tong = Artist.where(name: 'Pete Tong', soundcloud_url: 'https://soundcloud.com/petetong', soundcloud_track_url: 'https://soundcloud.com/eatseverything/pete-tong-b2b-eats-everything').first_or_create
proxy = Artist.where(name: 'Proxy', soundcloud_url: 'https://soundcloud.com/useproxy', soundcloud_track_url: 'https://soundcloud.com/useproxy/summergeddon-mix-2014').first_or_create
robbie_rivera = Artist.where(name: 'Robbie Rivera', soundcloud_url: 'https://soundcloud.com/robbierivera', soundcloud_track_url: 'https://soundcloud.com/thisisprovoke/robbie-rivera-live-at-maison').first_or_create
sandro_silva = Artist.where(name: 'Sandro Silva', soundcloud_url: 'https://soundcloud.com/djsandrosilva', soundcloud_track_url: 'https://soundcloud.com/djsandrosilva/sandro-silva-live-at-the-super').first_or_create
sasha = Artist.where(name: 'Sasha', soundcloud_url: 'https://soundcloud.com/sashaofficial', soundcloud_track_url: 'https://soundcloud.com/sashaofficial/last-night-on-earth-nye-show').first_or_create
scuba = Artist.where(name: 'Scuba', soundcloud_url: 'https://soundcloud.com/hotflush', soundcloud_track_url: 'https://soundcloud.com/platform/scuba-60-min-boiler-room').first_or_create
seven_lions = Artist.where(name: 'Seven Lions', soundcloud_url: 'https://soundcloud.com/seven-lions', soundcloud_track_url: 'https://soundcloud.com/seven-lions/live-ultra-owsla-stage-03-16').first_or_create
showtek = Artist.where(name: 'Showtek', soundcloud_url: 'https://soundcloud.com/showtekmusic', soundcloud_track_url: 'https://soundcloud.com/showtekmusic/showtek-live-ultra-miami-2014').first_or_create
sick_individuals = Artist.where(name: 'Sick Individuals', soundcloud_url: 'https://soundcloud.com/sickindividuals', soundcloud_track_url: 'https://soundcloud.com/sickindividuals/sick-individuals-live-sensation-russia').first_or_create
stefano_noferini_b2b_sian = Artist.where(name: 'Stefano Noferini B2B Sian', soundcloud_url: 'https://soundcloud.com/stefano-noferini', soundcloud_track_url: 'https://soundcloud.com/octopusrecordings/sian-2-meters-above-midnight').first_or_create
sub_focus = Artist.where(name: 'Sub Focus', soundcloud_url: 'https://soundcloud.com/subfocus', soundcloud_track_url: 'https://soundcloud.com/subfocus/sub-focus-mistajam-mix-may').first_or_create
swanky_tunes = Artist.where(name: 'Swanky Tunes', soundcloud_url: 'https://soundcloud.com/swankytunes', soundcloud_track_url: 'https://soundcloud.com/sandervandoorn/sander-van-doorn-identity-224').first_or_create
tensnake = Artist.where(name: 'Tensnake', soundcloud_url: 'https://soundcloud.com/tensnake', soundcloud_track_url: 'https://soundcloud.com/tensnake/essentialmix-tensnake').first_or_create
the_chainsmokers = Artist.where(name: 'The Chainsmokers', soundcloud_url: 'https://soundcloud.com/thechainsmokers', soundcloud_track_url: 'https://soundcloud.com/thechainsmokers/tcs-ultra-mainstage').first_or_create
the_magician = Artist.where(name: 'The Magician', soundcloud_url: 'https://soundcloud.com/themagician', soundcloud_track_url: 'https://soundcloud.com/earmilk/the-magician-goes-hard-with-earmilk').first_or_create
thomas_newson = Artist.where(name: 'Thomas Newson', soundcloud_url: 'https://soundcloud.com/thomasnewson', soundcloud_track_url: 'https://soundcloud.com/armadamusic/armada-night-radio-005-thomas-newson-guest-mix').first_or_create
tjr = Artist.where(name: 'TJR', soundcloud_url: 'https://soundcloud.com/tjr', soundcloud_track_url: 'https://soundcloud.com/tjr/tjr-umf-2014').first_or_create
tritonal = Artist.where(name: 'Tritonal', soundcloud_url: 'https://soundcloud.com/tritonalmusic', soundcloud_track_url: 'https://soundcloud.com/tritonalmusic/tritonia-050').first_or_create
uz = Artist.where(name: 'UZ', soundcloud_url: 'https://soundcloud.com/ball-trap-music', soundcloud_track_url: 'https://soundcloud.com/proxychen/uz-trap-shit-v13-justin-martin').first_or_create
vicetone = Artist.where(name: 'Vicetone', soundcloud_url: 'https://soundcloud.com/vicetone', soundcloud_track_url: 'https://soundcloud.com/vicetone/vicetone-ultra-music-festival-2014').first_or_create
victor_calderone = Artist.where(name: 'Victor Calderone', soundcloud_url: 'https://soundcloud.com/victorcalderone', soundcloud_track_url: 'https://soundcloud.com/victorcalderone/victor-calderone-drumcode').first_or_create
w_and_w = Artist.where(name: 'W&W', soundcloud_url: 'https://soundcloud.com/wandw', soundcloud_track_url: 'https://soundcloud.com/wandw/w-w-live-ultra-music-festival').first_or_create
what_so_not = Artist.where(name: 'What So Not', soundcloud_url: 'https://soundcloud.com/whatsonot', soundcloud_track_url: 'https://soundcloud.com/brenzo/wolfgang-gartner-coachella').first_or_create
wolfgang_gartner = Artist.where(name: 'Wolfgang Gartner', soundcloud_url: 'https://soundcloud.com/wolfganggartner', soundcloud_track_url: 'https://soundcloud.com/brenzo/wolfgang-gartner-coachella').first_or_create
wolfpack = Artist.where(name: 'Wolfpack', soundcloud_url: 'https://soundcloud.com/wolfpack', soundcloud_track_url: 'https://soundcloud.com/wolfpack/wolfpack-live-at-tomorrowland').first_or_create
zedd = Artist.where(name: 'Zedd', soundcloud_url: 'https://soundcloud.com/zedd', soundcloud_track_url: 'https://soundcloud.com/zedd/zedd-djmix').first_or_create
zeds_dead = Artist.where(name: 'Zeds Dead', soundcloud_url: 'https://soundcloud.com/zedsdead', soundcloud_track_url: 'https://soundcloud.com/zedsdead/zeds-dead-2014-diplo-and-friends-mix').first_or_create
zomboy = Artist.where(name: 'Zomboy', soundcloud_url: 'https://soundcloud.com/zomboy', soundcloud_track_url: 'https://soundcloud.com/zomboy/sets/the-dead-symphonic-e-p').first_or_create

Event.where(festival: electric_zoo, artist: alan_fitzpatrick).first_or_create
Event.where(festival: electric_zoo, artist: alesso).first_or_create
Event.where(festival: electric_zoo, artist: alvin_risk).first_or_create
Event.where(festival: electric_zoo, artist: ame).first_or_create
Event.where(festival: electric_zoo, artist: andrea_oliva).first_or_create
Event.where(festival: electric_zoo, artist: apollonia).first_or_create
Event.where(festival: electric_zoo, artist: armin_van_buuren).first_or_create
Event.where(festival: electric_zoo, artist: arty).first_or_create
Event.where(festival: electric_zoo, artist: atb).first_or_create
Event.where(festival: electric_zoo, artist: a_trak).first_or_create
Event.where(festival: electric_zoo, artist: audien).first_or_create
Event.where(festival: electric_zoo, artist: been_trill).first_or_create
Event.where(festival: electric_zoo, artist: benny_benassi).first_or_create
Event.where(festival: electric_zoo, artist: bingo_players).first_or_create
Event.where(festival: electric_zoo, artist: bonobo).first_or_create
Event.where(festival: tomorrowworld, artist: borgeous).first_or_create
Event.where(festival: tomorrowworld, artist: brillz).first_or_create
Event.where(festival: tomorrowworld, artist: bt).first_or_create
Event.where(festival: tomorrowworld, artist: caked_up).first_or_create
Event.where(festival: tomorrowworld, artist: candyland).first_or_create
Event.where(festival: tomorrowworld, artist: carlo_lio).first_or_create
Event.where(festival: tomorrowworld, artist: carnage).first_or_create
Event.where(festival: tomorrowworld, artist: cazzette).first_or_create
Event.where(festival: tomorrowworld, artist: chase_and_status).first_or_create
Event.where(festival: tomorrowworld, artist: chris_liebing).first_or_create
Event.where(festival: tomorrowworld, artist: clockwork).first_or_create
Event.where(festival: decibel, artist: cosmic_gate, start_time: DateTime.new(2014, 07, 19, 13, 00), end_time: DateTime.new(2014, 07, 19, 14, 00), venue: stage_1).first_or_create
Event.where(festival: decibel, artist: dada_life, start_time: DateTime.new(2014, 07, 19, 13, 45), end_time: DateTime.new(2014, 07, 19, 14, 45), venue: stage_2).first_or_create
Event.where(festival: decibel, artist: danny_avila, start_time: DateTime.new(2014, 07, 19, 13, 55), end_time: DateTime.new(2014, 07, 19, 14, 50), venue: stage_3).first_or_create
Event.where(festival: decibel, artist: danny_tenaglia, start_time: DateTime.new(2014, 07, 19, 14, 30), end_time: DateTime.new(2014, 07, 19, 15, 30), venue: stage_1).first_or_create
Event.where(festival: decibel, artist: dash_berlin, start_time: DateTime.new(2014, 07, 19, 14, 50), end_time: DateTime.new(2014, 07, 19, 15, 45), venue: stage_2).first_or_create
Event.where(festival: decibel, artist: datsik, start_time: DateTime.new(2014, 07, 19, 15, 20), end_time: DateTime.new(2014, 07, 19, 16, 20), venue: stage_3).first_or_create
Event.where(festival: decibel, artist: david_guetta, start_time: DateTime.new(2014, 07, 19, 15, 45), end_time: DateTime.new(2014, 07, 19, 16, 45), venue: stage_1).first_or_create
Event.where(festival: decibel, artist: david_solano, start_time: DateTime.new(2014, 07, 19, 16, 15), end_time: DateTime.new(2014, 07, 19, 17, 15), venue: stage_2).first_or_create
Event.where(festival: decibel, artist: deniz_koyu, start_time: DateTime.new(2014, 07, 19, 16, 45), end_time: DateTime.new(2014, 07, 19, 17, 45), venue: stage_3).first_or_create
Event.where(festival: decibel, artist: deorro, start_time: DateTime.new(2014, 07, 19, 17, 15), end_time: DateTime.new(2014, 07, 19, 18, 15), venue: stage_1).first_or_create
Event.where(festival: decibel, artist: destroid, start_time: DateTime.new(2014, 07, 19, 17, 45), end_time: DateTime.new(2014, 07, 19, 18, 45), venue: stage_2).first_or_create
Event.where(festival: decibel, artist: dimitri_vegas_and_like_mike, start_time: DateTime.new(2014, 07, 19, 18, 15), end_time: DateTime.new(2014, 07, 19, 19, 15), venue: stage_3).first_or_create
Event.where(festival: decibel, artist: dirty_south, start_time: DateTime.new(2014, 07, 19, 18, 45), end_time: DateTime.new(2014, 07, 19, 19, 45), venue: stage_1).first_or_create
Event.where(festival: bpm, artist: dirtyphonics).first_or_create
Event.where(festival: bpm, artist: dubfire).first_or_create
Event.where(festival: bpm, artist: dvbbs).first_or_create
Event.where(festival: bpm, artist: dyro).first_or_create
Event.where(festival: bpm, artist: fedde_le_grand).first_or_create
Event.where(festival: bpm, artist: feenixpawl).first_or_create
Event.where(festival: bpm, artist: fehrplay).first_or_create
Event.where(festival: bpm, artist: felix_cartal).first_or_create
Event.where(festival: bpm, artist: figure).first_or_create
Event.where(festival: bpm, artist: firebeatz).first_or_create
Event.where(festival: bpm, artist: gesaffelstein).first_or_create
Event.where(festival: bpm, artist: gladiator).first_or_create
Event.where(festival: bpm, artist: gorgon_city).first_or_create
Event.where(festival: bpm, artist: griz).first_or_create
Event.where(festival: bpm, artist: henry_fong).first_or_create
Event.where(festival: bpm, artist: heroes_x_villains).first_or_create
Event.where(festival: boston_calling, artist: hook_n_sling).first_or_create
Event.where(festival: boston_calling, artist: hot_since_82).first_or_create
Event.where(festival: boston_calling, artist: jack_u).first_or_create
Event.where(festival: boston_calling, artist: jamie_xx).first_or_create
Event.where(festival: boston_calling, artist: jeremy_olander).first_or_create
Event.where(festival: boston_calling, artist: joel_mull).first_or_create
Event.where(festival: boston_calling, artist: joseph_capriati).first_or_create
Event.where(festival: boston_calling, artist: josh_wink).first_or_create
Event.where(festival: boston_calling, artist: kaskade).first_or_create
Event.where(festival: boston_calling, artist: keys_n_krates).first_or_create
Event.where(festival: boston_calling, artist: kidnap_kid).first_or_create
Event.where(festival: boston_calling, artist: kill_paris).first_or_create
Event.where(festival: boston_calling, artist: kill_the_noise).first_or_create
Event.where(festival: boston_calling, artist: knife_party).first_or_create
Event.where(festival: boston_calling, artist: kove).first_or_create
Event.where(festival: boston_calling, artist: laidback_luke).first_or_create
Event.where(festival: boston_calling, artist: late_night_alumni).first_or_create
Event.where(festival: lollapalooza, artist: le_castle_vania).first_or_create
Event.where(festival: lollapalooza, artist: loudpvck).first_or_create
Event.where(festival: lollapalooza, artist: madeon).first_or_create
Event.where(festival: lollapalooza, artist: makj).first_or_create
Event.where(festival: lollapalooza, artist: mat_zo).first_or_create
Event.where(festival: lollapalooza, artist: milo_and_otis).first_or_create
Event.where(festival: lollapalooza, artist: morgan_page).first_or_create
Event.where(festival: lollapalooza, artist: moti).first_or_create
Event.where(festival: lollapalooza, artist: myon_and_shane_54).first_or_create
Event.where(festival: lollapalooza, artist: nervo).first_or_create
Event.where(festival: lollapalooza, artist: netsky).first_or_create
Event.where(festival: lollapalooza, artist: new_world_sound).first_or_create
Event.where(festival: lollapalooza, artist: nicky_romero).first_or_create
Event.where(festival: lollapalooza, artist: nicole_moudaber).first_or_create
Event.where(festival: electric_zoo, artist: oliver_heldens).first_or_create
Event.where(festival: electric_zoo, artist: ookay_b2b_kennedy_jones).first_or_create
Event.where(festival: electric_zoo, artist: otto_knows).first_or_create
Event.where(festival: electric_zoo, artist: paris_blohm).first_or_create
Event.where(festival: electric_zoo, artist: paul_van_dyk).first_or_create
Event.where(festival: electric_zoo, artist: pegboard_nerds).first_or_create
Event.where(festival: electric_zoo, artist: pete_tong).first_or_create
Event.where(festival: electric_zoo, artist: proxy).first_or_create
Event.where(festival: electric_zoo, artist: robbie_rivera).first_or_create
Event.where(festival: electric_zoo, artist: sandro_silva).first_or_create
Event.where(festival: electric_zoo, artist: sasha).first_or_create
Event.where(festival: tomorrowworld, artist: scuba).first_or_create
Event.where(festival: tomorrowworld, artist: seven_lions).first_or_create
Event.where(festival: tomorrowworld, artist: showtek).first_or_create
Event.where(festival: tomorrowworld, artist: sick_individuals).first_or_create
Event.where(festival: tomorrowworld, artist: stefano_noferini_b2b_sian).first_or_create
Event.where(festival: tomorrowworld, artist: sub_focus).first_or_create
Event.where(festival: tomorrowworld, artist: swanky_tunes).first_or_create
Event.where(festival: tomorrowworld, artist: tensnake).first_or_create
Event.where(festival: tomorrowworld, artist: the_chainsmokers).first_or_create
Event.where(festival: tomorrowworld, artist: the_magician).first_or_create
Event.where(festival: tomorrowworld, artist: thomas_newson).first_or_create
Event.where(festival: tomorrowworld, artist: tjr).first_or_create
Event.where(festival: tomorrowworld, artist: tritonal).first_or_create
Event.where(festival: tomorrowworld, artist: uz).first_or_create
Event.where(festival: decibel, artist: vicetone, start_time: DateTime.new(2014, 07, 18, 15, 20), end_time: DateTime.new(2014, 07, 18, 16, 15), venue: stage_1).first_or_create
Event.where(festival: decibel, artist: victor_calderone, start_time: DateTime.new(2014, 07, 18, 15, 30), end_time: DateTime.new(2014, 07, 18, 16, 30), venue: stage_2).first_or_create
Event.where(festival: decibel, artist: w_and_w, start_time: DateTime.new(2014, 07, 18, 16, 15), end_time: DateTime.new(2014, 07, 18, 17, 15), venue: stage_3).first_or_create
Event.where(festival: decibel, artist: what_so_not, start_time: DateTime.new(2014, 07, 18, 16, 35), end_time: DateTime.new(2014, 07, 18, 17, 35), venue: stage_1).first_or_create
Event.where(festival: decibel, artist: wolfgang_gartner, start_time: DateTime.new(2014, 07, 18, 17, 15), end_time: DateTime.new(2014, 07, 18, 18, 15), venue: stage_2).first_or_create
Event.where(festival: decibel, artist: wolfpack, start_time: DateTime.new(2014, 07, 18, 17, 30), end_time: DateTime.new(2014, 07, 18, 18, 30), venue: stage_3).first_or_create
Event.where(festival: decibel, artist: zedd, start_time: DateTime.new(2014, 07, 18, 18, 15), end_time: DateTime.new(2014, 07, 18, 19, 15), venue: stage_1).first_or_create
Event.where(festival: decibel, artist: zeds_dead, start_time: DateTime.new(2014, 07, 18, 18, 25), end_time: DateTime.new(2014, 07, 18, 19, 25), venue: stage_2).first_or_create
Event.where(festival: decibel, artist: zomboy, start_time: DateTime.new(2014, 07, 18, 19, 15), end_time: DateTime.new(2014, 07, 18, 20, 15), venue: stage_3).first_or_create

Tracker.where(subject: 'user_play').each do |tracker|
  tracker.update_attribute :count, rand(10) + rand(100)
end

Tracker.where(subject: 'user_save_to_schedule').each do |tracker|
  tracker.update_attribute :count, rand(30)
end

User.where(first_name: 'James', last_name: 'Zhang', email: 'jamesfzhang@gmail.com', admin: true).first_or_create
User.where(first_name: 'Divu', last_name: 'Jain', email: 'divanshuj@gmail.com', admin: true).first_or_create
User.where(first_name: 'Han', last_name: 'Chen', email: 'chenhan22@gmail.com', admin: true).first_or_create
